version: '3.9'

services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    command: uvicorn holowhoslive.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
      - redis
    environment:
      - DEV=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://:@redis:6379
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis

  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - 8080:8080
    command: npm run serve
    depends_on:
      - server

volumes:
  db_data:
