"""yt_channels and groups

Revision ID: 9a60dd025a69
Revises: 
Create Date: 2021-09-23 03:23:21.278240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a60dd025a69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_index(op.f('ix_groups_platform'), 'groups', ['platform'], unique=False)
    op.create_table('yt_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yt_channels_channel_id'), 'yt_channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_yt_channels_first_name'), 'yt_channels', ['first_name'], unique=False)
    op.create_index(op.f('ix_yt_channels_group'), 'yt_channels', ['group'], unique=False)
    op.create_index(op.f('ix_yt_channels_id'), 'yt_channels', ['id'], unique=False)
    op.create_index(op.f('ix_yt_channels_last_name'), 'yt_channels', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yt_channels_last_name'), table_name='yt_channels')
    op.drop_index(op.f('ix_yt_channels_id'), table_name='yt_channels')
    op.drop_index(op.f('ix_yt_channels_group'), table_name='yt_channels')
    op.drop_index(op.f('ix_yt_channels_first_name'), table_name='yt_channels')
    op.drop_index(op.f('ix_yt_channels_channel_id'), table_name='yt_channels')
    op.drop_table('yt_channels')
    op.drop_index(op.f('ix_groups_platform'), table_name='groups')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
