"""empty message

Revision ID: f4057f6212a0
Revises: 9a60dd025a69
Create Date: 2021-09-23 18:08:34.785443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4057f6212a0'
down_revision = '9a60dd025a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_channels', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_index('ix_yt_channels_group', table_name='yt_channels')
    op.create_foreign_key(None, 'yt_channels', 'groups', ['group_id'], ['id'])
    op.drop_column('yt_channels', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_channels', sa.Column('group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'yt_channels', type_='foreignkey')
    op.create_index('ix_yt_channels_group', 'yt_channels', ['group'], unique=False)
    op.drop_column('yt_channels', 'group_id')
    # ### end Alembic commands ###
